Feature/solid
polinas888/CategoryNoteApp pull request #2
Opened 2022-10-14 09:40 UTC by polinas888

solid principles for app

2022-10-25 07:53 UTC, polinas888 commented on app/src/main/java/com/example/categorynoteapp/MainActivity.kt
> +    private fun setupFirstFragmentIfNotSetup(savedInstanceState: Bundle?, supportFragmentManager: FragmentManager) {
done

2022-10-25 08:59 UTC, polinas888 commented on app/src/main/java/com/example/categorynoteapp/ui/category/CategoryFragment.kt
> +                categoryViewModel.saveCategory(newCategory)
done

2022-10-25 09:06 UTC, polinas888 commented on app/src/main/java/com/example/categorynoteapp/ui/category/CategoryFragment.kt
> +                    categoryViewModel.categoryListLiveData.observe(viewLifecycleOwner) { categories ->
done

2022-10-25 09:37 UTC, polinas888 commented on app/src/main/java/com/example/categorynoteapp/ui/category/CategoryFragment.kt
> +    private fun saveNewCategoryIfExist(data: Intent?) {
done

2022-10-25 09:41 UTC, polinas888 commented on app/src/main/java/com/example/categorynoteapp/ui/category/CategoryViewModel.kt
> +//Single Responsibility Principle class include only functionality how to get and safe data for category
done

2022-10-25 09:42 UTC, polinas888 commented on app/src/main/java/com/example/categorynoteapp/ui/category/CreateCategoryDialogFragment.kt
> +    private fun runOnActivityResultAndPassCategoryArg() {
done

2022-10-25 09:44 UTC, polinas888 commented on app/src/main/java/com/example/categorynoteapp/ui/notification/NoteCreateOrChangeFragment.kt
> +class NoteCreateOrChangeFragment : Fragment() {
a-ha... very clever:) Done

2022-10-25 09:49 UTC, polinas888 commented on app/src/main/java/com/example/categorynoteapp/ui/notification/NoteFragment.kt
> +                    }
done

2022-10-25 09:50 UTC, polinas888 commented on app/src/main/java/com/example/categorynoteapp/ui/notification/NoteFragment.kt
> +            if (note != null) {
done

2022-10-25 10:08 UTC, polinas888 commented on app/src/main/java/com/example/categorynoteapp/ui/category/CategoryFragment.kt
> +                    categoryViewModel.loadData()
CategoryFragment doesnt recreated so I need loadData here too

2022-10-25 10:11 UTC, polinas888 commented on app/src/main/java/com/example/categorynoteapp/ui/notification/NoteFragment.kt
> +        binding.addButton.setOnClickListener {
done

2022-10-25 10:12 UTC, polinas888 commented on app/src/main/java/com/example/categorynoteapp/ui/notification/NoteFragment.kt
> +    private fun setupDataOrEmptyListOnUi(notes: List<Note>) {
done

2022-10-25 10:18 UTC, polinas888 commented on app/src/main/java/com/example/categorynoteapp/ui/notification/NoteFragment.kt
> +            noteViewModel.noteListLiveData.value?.let {
removed method but I still have to loadData after save because NoteFragment doesnt recreated

2022-10-25 10:19 UTC, polinas888 commented on app/src/main/java/com/example/categorynoteapp/ui/notification/NoteFragment.kt
> +    private fun updateUiAfterChange() {
it stays a secret forever because removed this method:)

2022-10-25 10:24 UTC, polinas888 commented on app/src/main/java/com/example/categorynoteapp/ui/notification/NoteFragment.kt
> +    private suspend fun openFragmentUpdateNote(noteText: String) {
done

2022-10-27 06:35 UTC, polinas888 commented on app/src/main/java/com/example/categorynoteapp/ui/notification/NoteFragment.kt
> +        noteAdapter = NoteAdapter((notes),
done

2022-10-27 06:37 UTC, polinas888 commented on app/src/main/java/com/example/categorynoteapp/ui/notification/NoteFragment.kt
> +        val args = Bundle()
done

2022-10-27 06:40 UTC, polinas888 commented on app/src/main/java/com/example/categorynoteapp/ui/notification/NoteFragment.kt
> +            noteViewModel.noteListLiveData.observe(viewLifecycleOwner) { notes ->
done

2022-10-27 06:43 UTC, polinas888 commented on app/src/main/java/com/example/categorynoteapp/ui/notification/NoteViewModel.kt
> +    private suspend fun getNotes(categoryId: Int): DataResult<List<Note>> {
done

2022-10-27 07:50 UTC, polinas888 commented on app/src/main/java/com/example/categorynoteapp/ui/category/CategoryFragment.kt
> +        val dialog = CreateCategoryDialogFragment()
changed deprecated getTargetFragment to getResultFragment

2022-10-31 17:00 UTC, asavinski requested changes

2022-10-31 17:00 UTC, asavinski commented on app/src/main/java/com/example/categorynoteapp/Extentions.kt
> +    val manager: FragmentManager = requireActivity().supportFragmentManager
better use parentFragmentManager. Read this [article](https://developer.android.com/guide/fragments/fragmentmanager)

2022-10-31 17:00 UTC, asavinski commented on app/src/main/java/com/example/categorynoteapp/Extentions.kt
>  fun Fragment.changeFragment(args: Bundle, fragmentManager: FragmentManager) {
For navigation in activity better use function like this.
`Activity.changeFragment(newFragment: Fragment, args: Bundle, contaierID : Int = R.id.container)`

2022-10-31 17:00 UTC, asavinski commented on app/src/main/java/com/example/categorynoteapp/ui/category/CategoryFragment.kt
> +const val CREATE_CATEGORY_FRAGMENT = "create_category_fragment"
rename to CREATE_CATEGORY_EVENT

2022-10-31 17:00 UTC, asavinski commented on app/src/main/java/com/example/categorynoteapp/ui/notification/NoteViewModel.kt
> +    suspend fun openFragmentUpdateNote(noteText: String, noteIdForUpdate: Int, categoryId: Int) {
Yon name this fun openFragment... but it doesn't open anything.

2022-11-02 06:04 UTC, polinas888 commented on app/src/main/java/com/example/categorynoteapp/ui/category/CategoryFragment.kt
> +    private fun setUpData() {
done

2022-11-02 07:11 UTC, polinas888 commented on app/src/main/java/com/example/categorynoteapp/ui/notification/NoteFragment.kt
> +            noteAdapter = NoteAdapter((note),
changed for note and for category

2022-11-02 07:15 UTC, polinas888 commented on app/src/main/java/com/example/categorynoteapp/ui/category/CategoryFragment.kt
> +        setUpData()
done

2022-11-02 07:40 UTC, polinas888 commented on app/src/main/java/com/example/categorynoteapp/Extentions.kt
>  fun Fragment.changeFragment(args: Bundle, fragmentManager: FragmentManager) {
done

2022-11-03 13:19 UTC, polinas888 commented on app/src/main/java/com/example/categorynoteapp/ui/category/CategoryFragment.kt
> +const val CREATE_CATEGORY_FRAGMENT = "create_category_fragment"
done

2022-11-03 13:20 UTC, polinas888 commented on app/src/main/java/com/example/categorynoteapp/ui/notification/NoteViewModel.kt
> +    suspend fun openFragmentUpdateNote(noteText: String, noteIdForUpdate: Int, categoryId: Int) {
renamed

2022-11-03 13:39 UTC, polinas888 commented on app/src/main/java/com/example/categorynoteapp/Extentions.kt
> +    val manager: FragmentManager = requireActivity().supportFragmentManager
gone

2022-11-10 11:42 UTC, asavinski approved these changes

2022-11-17 10:09 UTC, merged